# Batch Build DGE_SDK


g : cam cube vbo dup dvbo gtex dtex gtexm dtexm glgt dlgt gblnd dblnd dmdl

cam:
	cd 1dge_cam; $(MAKE) -e 'tpf=wiz'

cube:
	cd 2gl_cube; $(MAKE) -e 'tpf=wiz'

vbo:
	cd 2gl_vbo; $(MAKE) -e 'tpf=wiz'



dup:
	cd 3dge_up; $(MAKE) -e 'tpf=wiz'

dvbo:
	cd 3dge_vbo; $(MAKE) -e 'tpf=wiz'



gtex:
	cd 4gl_tex; $(MAKE) -e 'tpf=wiz'

dtex:
	cd 4dge_tex; $(MAKE) -e 'tpf=wiz'


gtexm:
	cd 5gl_multi; $(MAKE) -e 'tpf=wiz'

dtexm:
	cd 5dge_multi; $(MAKE) -e 'tpf=wiz'


glgt:
	cd 6gl_lgt; $(MAKE) -e 'tpf=wiz'

dlgt:
	cd 6dge_lgt; $(MAKE) -e 'tpf=wiz'


gblnd:
	cd 7gl_blend; $(MAKE) -e 'tpf=wiz'

dblnd:
	cd 7dge_blend; $(MAKE) -e 'tpf=wiz'

dmdl:
	cd 9dge_mdl; $(MAKE) -e 'tpf=wiz'

