# Batch Build DGE_SDK


g : dgt_lzo sptmx vk

dgt_lzo:
	cd 1dgtlzo; $(MAKE) -e 'tpf=wiz'

sptmx:
	cd 3spritem; $(MAKE) -e 'tpf=wiz'

vk:
	cd 4vkb; $(MAKE) -e 'tpf=wiz'

drm:
	cd 5drm; $(MAKE) -e 'tpf=wiz'



