# Batch Build DGE_SDK


g : cam cube vbo dup dvbo gtex dtex gtexm dtexm glgt dlgt gblnd dblnd dase mdl

cam:
	cd 1dge_cam; $(MAKE) -e 'tpf=n35'

cube:
	cd 2gl_cube; $(MAKE) -e 'tpf=n35'

vbo:
	cd 2gl_vbo; $(MAKE) -e 'tpf=n35'



dup:
	cd 3dge_up; $(MAKE) -e 'tpf=n35'

dvbo:
	cd 3dge_vbo; $(MAKE) -e 'tpf=n35'



gtex:
	cd 4gl_tex; $(MAKE) -e 'tpf=n35'

dtex:
	cd 4dge_tex; $(MAKE) -e 'tpf=n35'


gtexm:
	cd 5gl_multi; $(MAKE) -e 'tpf=n35'

dtexm:
	cd 5dge_multi; $(MAKE) -e 'tpf=n35'


glgt:
	cd 6gl_lgt; $(MAKE) -e 'tpf=n35'

dlgt:
	cd 6dge_lgt; $(MAKE) -e 'tpf=n35'


gblnd:
	cd 7gl_blend; $(MAKE) -e 'tpf=n35'

dblnd:
	cd 7dge_blend; $(MAKE) -e 'tpf=n35'


dase:
	cd 9dge_ase; $(MAKE) -e 'tpf=n35'

mdl:
	cd 9dge_mdl; $(MAKE) -e 'tpf=n35'

