# Batch Build DGE_SDK


g : sys dev sprite font input vol al sound client server lua grav viv

sys:
	cd 1system; $(MAKE) -e 'tpf=n35'

dev:
	cd 2device; $(MAKE) -e 'tpf=n35'

sprite:
	cd 3sprite; $(MAKE) -e 'tpf=n35'

font:
	cd 3font; $(MAKE) -e 'tpf=n35'

input:
	cd 4input; $(MAKE) -e 'tpf=n35'

vol:
	cd 5volume; $(MAKE) -e 'tpf=n35'

al:
	cd 5openal; $(MAKE) -e 'tpf=n35'

sound:
	cd 5sound; $(MAKE) -e 'tpf=n35'

client:
	cd 6tcpclient; $(MAKE) -e 'tpf=n35'

server:
	cd 6tcpserver; $(MAKE) -e 'tpf=n35'

lua:
	cd 8lua; $(MAKE) -e 'tpf=n35'

grav:
	cd 7gravity; $(MAKE) -e 'tpf=n35'

viv:
	cd 7vibration; $(MAKE) -e 'tpf=n35'

