# Batch Build DGE_SDK


g : dgt_lzo sptmx vk

dgt_lzo:
	cd 1dgtlzo; $(MAKE) -e 'tpf=n35'

sptmx:
	cd 3spritem; $(MAKE) -e 'tpf=n35'

vk:
	cd 4vkb; $(MAKE) -e 'tpf=n35'


#drm:
#	cd 5drm; $(MAKE) -e 'tpf=n35'



