# Batch Build DGE_SDK


g : sys dev sprite font input vol al sound client server lua

sys:
	cd 1system; $(MAKE) -e 'tpf=wiz'

dev:
	cd 2device; $(MAKE) -e 'tpf=wiz'

sprite:
	cd 3sprite; $(MAKE) -e 'tpf=wiz'

font:
	cd 3font; $(MAKE) -e 'tpf=wiz'

input:
	cd 4input; $(MAKE) -e 'tpf=wiz'

vol:
	cd 5volume; $(MAKE) -e 'tpf=wiz'

al:
	cd 5openal; $(MAKE) -e 'tpf=wiz'

sound:
	cd 5sound; $(MAKE) -e 'tpf=wiz'

client:
	cd 6tcpclient; $(MAKE) -e 'tpf=wiz'

server:
	cd 6tcpserver; $(MAKE) -e 'tpf=wiz'

lua:
	cd 8lua; $(MAKE) -e 'tpf=wiz'
