# Batch Build DGE_SDK


g : lua al alut dge dgx dgt

lua:
	cd 02lua503; $(MAKE) -e 'tpf=n35'
	
al:
	cd 02openal; $(MAKE) -e 'tpf=n35'

alut:
	cd 02openalut; $(MAKE) -e 'tpf=n35'

dge:
	cd 11dge20; $(MAKE) -e 'tpf=n35'

dgx:
	cd 12dgx20; $(MAKE) -e 'tpf=n35'

dgt:
	cd 13dgt20; $(MAKE) -e 'tpf=n35'
